name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set permissions for EC2 private key
        run : |
          echo "${{ secrets.AWS_KEY }}" > ec2-key.pem
          chmod 600 ec2-key.pem

      - name: Deploy to AWS EC2
        env:
          AWS_IP: ${{ secrets.AWS_IP }}
          AWS_USER: ${{ secrets.AWS_USER }}
          AWS_KEY: ${{ secrets.AWS_KEY }}
        run: |
          ssh -o StrictHostKeyChecking=no -i ec2-key.pem $AWS_USER@$AWS_IP "cd /home/$AWS_USER/projects/hng-devops-stage-zero-task && 
          git pull origin main && 
          sudo docker-compose build && 
          sudo docker-compose up -d"
          rm ec2-key.pem

      - name: Set permissions for GCE private key
        run: |
          echo "${{ secrets.GCP_KEY }}" > gce-key.pem
          chmod 600 gce-key.pem

      - name: Deploy to Google Compute Engine
        env:
          AWS_IP: ${{ secrets.GCP_IP }}
          AWS_USER: ${{ secrets.GCP_USER }}
          AWS_KEY: ${{ secrets.GCP_KEY }}
        run: |
          ssh -o StrictHostKeyChecking=no -i gce-key.pem $GCP_USER@$GCP_IP "cd /home/$GCP_USER/projects/hng-devops-stage-zero-task && 
          git pull origin main && 
          sudo docker-compose build && 
          sudo docker-compose up -d"
          rm gce-key.pem
