name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: <your_registry>.azurecr.io
        username: ${{ secrets.AZURECR_USERNAME }}
        password: ${{ secrets.AZURECR_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker-compose build
        docker-compose push

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: <your_app_name>
        slot-name: production
        images: |
          <your_registry>.azurecr.io/fastapi_app:latest
          <your_registry>.azurecr.io/nginx_server:latest
